"""
A large set of static parameters that have been used in the past to
assist with reading pystops. This has proven to be error prone, and so
more dynamic readers are now being used, These exist as a final check.
"""

from dataclasses import dataclass, field
from typing import List, Dict


@dataclass
class TableDef:
    table_id: str
    end_table_tag: str
    skip_rows: int = 0
    skip_column: int = 0
    widths: List[int] | None = None
    df_drop_top_rows: int | None = None
    df_drop_tail_rows: int | None = None
    reset_header: bool = False
    drop_row: List[int] | None = None
    read_row: List[int] | None = None
    drop_column: List[int] | None = None
    rename_columns: Dict[str, str] | None = None
    add_columns: List[str] | None = None
    add_columns_vals: List | None = None
    remove_char_column: str | None = None
    remove_char_column_str: str | None = None
    convert_numerics: bool = False
    int_columns: List[int] | None = None
    remove_str: str | None = None
    index_col: int | None = None
    melt_id_var: str | None = None
    melt_value_var: str | None = None
    melt_var_name: str | None = None
    melt_value_name: str | None = None


TABLE_PARAMETERS = {
    "1.01": TableDef(
        "1.01",
        end_table_tag="Control Filename",
        skip_rows=2,
        df_drop_top_rows=1,
        reset_header=False,
        rename_columns={
            "Run Parameters": "Scenario",
            "Unnamed: 1": "temp1",
            "Unnamed: 2": "temp2",
            "Unnamed: 3": "Year",
        },
        int_columns=["Year"],
        drop_column=["temp1", "temp2"],
        remove_char_column="Scenario",
        remove_char_column_str="Year:",
        convert_numerics=False,
    ),
    # Station Listing
    "1.02": TableDef(
        "1.02",
        end_table_tag=" Adjustment of",
        skip_rows=3,
        df_drop_top_rows=1,
        df_drop_tail_rows=4,
        reset_header=False,
        rename_columns=None,
        convert_numerics=False,
        int_columns=["BoardCount"],
        index_col=None,
    ),
    # Station Group Boardings Prior to Adjustment
    "2.04": TableDef(
        "2.04",
        end_table_tag="COUNT",
        skip_rows=10,
        df_drop_top_rows=1,
        df_drop_tail_rows=2,
        rename_columns={"Unnamed: 0": "origin"},
        index_col="origin",
        convert_numerics=True,
    ),
    # Station Group Boarding Factor for Application to Later Iterations
    "2.05": TableDef(
        "2.05",
        end_table_tag="-----------",
        skip_rows=5,
        df_drop_top_rows=1,
        df_drop_tail_rows=1,
        rename_columns={"Unnamed: 0": "origin"},
        index_col="origin",
        convert_numerics=True,
    ),
    # Type 10/12 Group-Level Calibration Summary-Stations/Stops
    "2.07": TableDef(
        "2.07",
        end_table_tag="-----------",
        skip_rows=8,  # 'df_drop_top_rows': 1,
        df_drop_tail_rows=1,
        reset_header=True,
        widths=[7, 11, 11, 11, 11],
        rename_columns={
            0: "station_group",
            1: "pre_calib_board",
            2: "station_count",
            3: "station_target",
            4: "post_calib_board",
        },
        convert_numerics=True,
        int_columns="station_group",
        index_col="station_group",
    ),
    # Type 11/12 Group-Level Calibration Summary-Station/Route Summary
    "2.08": TableDef(
        "2.08",
        end_table_tag="Number of unique",
        skip_rows=8,  # 'df_drop_top_rows': 1,
        df_drop_tail_rows=1,
        reset_header=True,
        widths=[6, 22, 11, 11, 11, 10],
        rename_columns={
            0: "route_group_num",
            1: "route_group",
            2: "pre_calib_board",
            3: "route_count",
            4: "route_target",
            5: "post_calib_board",
        },
        convert_numerics=True,  #'int_columns': 'station_group',
        index_col="route_group_num",
    ),
    # Station Group to Station Group Ridership-Existing
    "3.01": TableDef(
        "3.01",
        end_table_tag="TOTAL",
        skip_rows=8,
        df_drop_top_rows=1,
        index_col="origin",
        rename_columns={"Unnamed: 0": "origin"},
    ),
    # Station Group to Station Group Ridership-No-Build
    "3.02": TableDef(
        "3.02",
        end_table_tag="TOTAL",
        skip_rows=8,
        df_drop_top_rows=1,
        index_col="origin",
        rename_columns={"Unnamed: 0": "origin"},
    ),
    # Station Group to Station Group Ridership-Build
    "3.03": TableDef(
        "3.03",
        end_table_tag="TOTAL",
        skip_rows=8,
        df_drop_top_rows=1,
        index_col="origin",
        rename_columns={"Unnamed: 0": "origin"},
    ),
    # Weekday Linked District-to-District Transit Trips
    "4.01": TableDef(
        "4.01",
        end_table_tag="Total",
        skip_rows=5,
        df_drop_top_rows=1,
        rename_columns={"Idist": "origin"},
        melt_id_var=["origin"],
        melt_var_name="destination",
        melt_value_name="Transit Trip",
    ),
    # Weekday Incremental Linked Dist-to-Dist Transit Trips
    "4.02": TableDef(
        "4.02",
        end_table_tag="Total",
        skip_rows=5,
        df_drop_top_rows=1,
        rename_columns={"Idist": "origin"},
        melt_id_var=["origin"],
        melt_var_name="destination",
        melt_value_name="Transit Trip",
    ),
    # Weekday Linked District-to-District Project Trips
    "4.03": TableDef(
        "4.03",
        end_table_tag="Total",
        skip_rows=5,
        df_drop_top_rows=1,
        rename_columns={"Idist": "origin"},
        melt_id_var=["origin"],
        melt_var_name="destination",
        melt_value_name="Transit Trip",
    ),
    # Weekday Unlinked Station-to-Station Project Trips
    "4.04": TableDef(
        "4.04",
        end_table_tag="Total",
        skip_rows=5,
        df_drop_top_rows=1,
        rename_columns={"Unnamed: 0": "origin"},
        melt_id_var=["origin"],
        melt_var_name="destination",
        melt_value_name="Transit Trip",
    ),
    # Incremental District-to-District Vehicle PMT
    "8.01": TableDef(
        "8.01",
        end_table_tag="Total",
        skip_rows=5,
        df_drop_top_rows=1,
        rename_columns={"Idist": "origin"},
        melt_id_var=["origin"],
        melt_var_name="destination",
        melt_value_name="Incremental PMT",
    ),
    # Average Weekday Station Boardings by Mode of Access
    "9.01": TableDef(
        "9.01",
        end_table_tag="\x00",
        skip_rows=8,
        reset_header=True,
        rename_columns={
            0: "stop_id",
            1: "station_name",
            2: "EXST_wlk",
            3: "EXST_knr",
            4: "EXST_pnr",
            5: "EXST_xfr",
            6: "EXST_all",
            7: "NOBL_wlk",
            8: "NOBL_knr",
            9: "NOBL_pnr",
            10: "NOBL_xfr",
            11: "NOBL_all",
            12: "BLD_wlk",
            13: "BLD_knr",
            14: "BLD_pnr",
            15: "BLD_xfr",
            16: "BLD_all",
        },
        int_columns=[
            "EXST_wlk",
            "EXST_knr",
            "EXST_pnr",
            "EXST_xfr",
            "EXST_all",
            "NOBL_wlk",
            "NOBL_knr",
            "NOBL_pnr",
            "NOBL_xfr",
            "NOBL_all",
            "BLD_wlk",
            "BLD_knr",
            "BLD_pnr",
            "BLD_xfr",
            "BLD_all",
        ],
        melt_id_var=["stop_id", "station_name"],
        melt_value_var=[
            "EXST_wlk",
            "EXST_knr",
            "EXST_pnr",
            "EXST_xfr",
            "EXST_all",
            "NOBL_wlk",
            "NOBL_knr",
            "NOBL_pnr",
            "NOBL_xfr",
            "NOBL_all",
            "BLD_wlk",
            "BLD_knr",
            "BLD_pnr",
            "BLD_xfr",
            "BLD_all",
        ],
        melt_var_name="Type",
        melt_value_name="Transit Trip",
    ),
    # Average Weekday Route Boardings by Zone (Production-End) Access Type
    "10.01": TableDef(
        "10.01",
        end_table_tag="               Total",
        skip_rows=7,
        reset_header=True,
        widths=[25, 30] + [10] * 13,
        df_drop_top_rows=1,
        rename_columns={
            0: "route_id",
            1: "route_name",
            2: "route_count",
            3: "EXST_wlk",
            4: "EXST_knr",
            5: "EXST_pnr",
            6: "EXST_all",
            7: "NOBL_wlk",
            8: "NOBL_knr",
            9: "NOBL_pnr",
            10: "NOBL_all",
            11: "BLD_wlk",
            12: "BLD_knr",
            13: "BLD_pnr",
            14: "BLD_all",
        },
        int_columns=[
            "route_count",
            "EXST_wlk",
            "EXST_knr",
            "EXST_pnr",
            "EXST_all",
            "NOBL_wlk",
            "NOBL_knr",
            "NOBL_pnr",
            "NOBL_all",
            "BLD_wlk",
            "BLD_knr",
            "BLD_pnr",
            "BLD_all",
        ],
        melt_id_var=["route_id", "route_name", "route_count"],
        melt_value_var=[
            "EXST_wlk",
            "EXST_knr",
            "EXST_pnr",
            "EXST_all",
            "NOBL_wlk",
            "NOBL_knr",
            "NOBL_pnr",
            "NOBL_all",
            "BLD_wlk",
            "BLD_knr",
            "BLD_pnr",
            "BLD_all",
        ],
        melt_var_name="Type",
        melt_value_name="Transit Trip",
    ),
    # PEAK TRIPS, MILES AND HOURS BY ROUTE
    "10.03": TableDef(
        "10.03",
        end_table_tag="                                                  Total",
        skip_rows=8,
        remove_str="--",
        reset_header=True,
        widths=[25, 30, 7, 13, 13, 7, 13, 13, 7, 13, 13],
        df_drop_top_rows=1,
        rename_columns={
            0: "route_id",
            1: "route_name",
            2: "EXST_trips",
            3: "EXST_miles",
            4: "EXST_hours",
            5: "NOBL_trips",
            6: "NOBL_miles",
            7: "NOBL_hours",
            8: "BLD_trips",
            9: "BLD_miles",
            10: "BLD_hours",
        },
        melt_id_var=["route_id", "route_name"],
        melt_var_name="Service",
        melt_value_name="Measurements",
    ),
    # OFFPEAK TRIPS, MILES AND HOURS BY ROUTE
    "10.04": TableDef(
        "10.04",
        end_table_tag="                                                  Total",
        skip_rows=8,
        remove_str="--",
        reset_header=True,
        widths=[25, 30, 7, 13, 13, 7, 13, 13, 7, 13, 13],
        df_drop_top_rows=1,
        rename_columns={
            0: "route_id",
            1: "route_name",
            2: "EXST_trips",
            3: "EXST_miles",
            4: "EXST_hours",
            5: "NOBL_trips",
            6: "NOBL_miles",
            7: "NOBL_hours",
            8: "BLD_trips",
            9: "BLD_miles",
            10: "BLD_hours",
        },
        melt_id_var=["route_id", "route_name"],
        melt_var_name="Service",
        melt_value_name="Measurements",
    ),
    # Avgerage Weekday Route Boardings by Route Access Type
    "10.05": TableDef(
        "10.05",
        end_table_tag="               Total",
        skip_rows=7,
        remove_str="--",
        reset_header=True,
        widths=[25, 30, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        df_drop_top_rows=1,
        rename_columns={
            0: "route_id",
            1: "route_name",
            2: "counts",
            3: "EXST_WLK",
            4: "EXST_KNR",
            5: "EXST_PNR",
            6: "EXST_XFR",
            7: "EXST_ALL",
            8: "NOBL_WLK",
            9: "NOBL_KNR",
            10: "NOBL_PNR",
            11: "NOBL_XFR",
            12: "NOBL_ALL",
            13: "BLD_WLK",
            14: "BLD_KNR",
            15: "BLD_PNR",
            16: "BLD_XFR",
            17: "BLD_ALL",
        },
        melt_id_var=["route_id", "route_name", "counts"],
        melt_value_var=[
            "EXST_WLK",
            "EXST_KNR",
            "EXST_PNR",
            "EXST_XFR",
            "NOBL_WLK",
            "NOBL_KNR",
            "NOBL_PNR",
            "NOBL_XFR",
            "BLD_WLK",
            "BLD_KNR",
            "BLD_PNR",
            "BLD_XFR",
        ],
        melt_var_name="Scenario_MOA",
        melt_value_name="Transit Trip",
    ),
    # Home-Based Work
    "11.01": TableDef(
        "11.01",
        end_table_tag=". . . . . . .",
        skip_rows=6,
        reset_header=True,
        widths=[9, 20, 12, 1, 8, 8, 1, 8, 8, 1, 8, 8, 1, 8, 8, 1],
        df_drop_top_rows=1,
        df_drop_tail_rows=1,
        drop_row=["-|All"],
        rename_columns={
            0: "hh_car",
            1: "sub_mode",
            2: "access_mode",
            3: "dh1",
            4: "EXST_model",
            5: "EXST_survey",
            6: "dh2",
            7: "NOBL_model",
            8: "NOBL_survey",
            9: "dh3",
            10: "BLD_model",
            11: "BLD_survey",
            12: "dh4",
            13: "BLD_pj_model",
            14: "BLD_pj_survey",
        },
        add_columns="Purpose",
        add_columns_vals="HBW",
        melt_id_var=["hh_car", "sub_mode", "access_mode", "Purpose"],
        melt_value_var=[
            "EXST_model",
            "EXST_survey",
            "NOBL_model",
            "NOBL_survey",
            "BLD_model",
            "BLD_survey",
            "BLD_pj_model",
            "BLD_pj_survey",
        ],
        melt_var_name="Scenario",
        melt_value_name="Transit Trip",
    ),
    # Home-Based Other
    "11.02": TableDef(
        "11.02",
        end_table_tag=". . . . . . .",
        skip_rows=6,
        reset_header=True,
        widths=[9, 20, 12, 1, 8, 8, 1, 8, 8, 1, 8, 8, 1, 8, 8, 1],
        df_drop_top_rows=1,
        df_drop_tail_rows=1,
        drop_row=["-|All"],
        rename_columns={
            0: "hh_car",
            1: "sub_mode",
            2: "access_mode",
            3: "dh1",
            4: "EXST_model",
            5: "EXST_survey",
            6: "dh2",
            7: "NOBL_model",
            8: "NOBL_survey",
            9: "dh3",
            10: "BLD_model",
            11: "BLD_survey",
            12: "dh4",
            13: "BLD_pj_model",
            14: "BLD_pj_survey",
        },
        add_columns="Purpose",
        add_columns_vals="HBO",
        melt_id_var=["hh_car", "sub_mode", "access_mode", "Purpose"],
        melt_value_var=[
            "EXST_model",
            "EXST_survey",
            "NOBL_model",
            "NOBL_survey",
            "BLD_model",
            "BLD_survey",
            "BLD_pj_model",
            "BLD_pj_survey",
        ],
        melt_var_name="Scenario",
        melt_value_name="Transit Trip",
    ),
    # Non-Home Based
    "11.03": TableDef(
        "11.03",
        end_table_tag=". . . . . . .",
        skip_rows=6,
        remove_str=["-", "\|"],
        drop_row=["-|All"],
        reset_header=True,
        widths=[9, 20, 12, 1, 8, 8, 1, 8, 8, 1, 8, 8, 1, 8, 8, 1],
        df_drop_top_rows=1,
        df_drop_tail_rows=1,
        rename_columns={
            0: "hh_car",
            1: "sub_mode",
            2: "access_mode",
            3: "dh1",
            4: "EXST_model",
            5: "EXST_survey",
            6: "dh2",
            7: "NOBL_model",
            8: "NOBL_survey",
            9: "dh3",
            10: "BLD_model",
            11: "BLD_survey",
            12: "dh4",
            13: "BLD_pj_model",
            14: "BLD_pj_survey",
            15: "dh5",
        },
        add_columns="Purpose",
        add_columns_vals="NHB",
        melt_id_var=["hh_car", "sub_mode", "access_mode", "Purpose"],
        melt_value_var=[
            "EXST_model",
            "EXST_survey",
            "NOBL_model",
            "NOBL_survey",
            "BLD_model",
            "BLD_survey",
            "BLD_pj_model",
            "BLD_pj_survey",
        ],
        melt_var_name="Scenario",
        melt_value_name="Transit Trip",
    ),
    "SECTION 16": TableDef(
        "SECTION 16",
        end_table_tag="------------------------------------------------------------------------------------------------",
        df_drop_tail_rows=1,
        skip_rows=1,
        df_drop_top_rows=1,
    ),
    # Section 15
    "SECTION 15": TableDef(
        "SECTION 15",
        end_table_tag="SECTION 16",
        index_col="CARS",
        df_drop_tail_rows=2,
        skip_rows=2,
        df_drop_top_rows=1,
    ),
}
